# Generated by Django 4.0.1 on 2022-01-24 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0002_conversation_remove_message_receiver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='user1',
            field=models.CharField(default='user1', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conversation',
            name='user2',
            field=models.CharField(default='user2', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.CharField(choices=[(1, 'user1'), (2, 'user2')], max_length=10),
        ),
    ]
