# Generated by Django 4.0.1 on 2022-01-24 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0003_conversation_user1_conversation_user2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.CharField(choices=[('1', 'user1'), ('2', 'user2')], max_length=10),
        ),
    ]
